name: Deploy FastAPI to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Zip deployment package
        run: |
          zip -r release.zip api faiss_index requirements.txt startup.sh python3.10 -x "*.git*" "*.venv*" "__pycache__" "*.pyc"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-package
          path: release.zip

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: release-package

      - name: Unzip for deployment
        run: unzip release.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "rag-demo"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
